services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: database
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
  backend:
    image: fmahdi09/guthub-backend:latest
    environment:
      DATASOURCE_URL: ${BACKEND_DATASOURCE_URL}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      ACCESS_TOKEN_SECRET: ${BACKEND_ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${BACKEND_REFRESH_TOKEN_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "80:8080"

volumes:
  postgres:
