name: GutHub Backend 

on:
  push:
    paths:
      - .github/**
      - Backend/**

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint

    steps:
      - name: lint here
        run: echo "linting . . ."

  test:
    needs: lint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./Backend
    strategy:
      matrix:
        java: [ 23 ]

    name: Run tests on Java ${{ matrix.java }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: run unit tests
        run: mvn -B clean test -PUnit

      - name: run integration tests
        run: mvn -B clean test -PIntegration

  build:
    needs: test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./Backend
    strategy:
      matrix:
        java: [ 23 ]

    name: Build and analyze on Java ${{ matrix.java }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B install -DskipTests org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=FMahdi09_GutHub
