name: GutHub Backend 

on:
  push:
    paths:
      - .github/**
      - Backend/**

jobs:
  lint:
    runs-on: ubuntu-22.04
    name: Lint

    steps:
      - name: lint here
        run: echo "linting . . ."

  test:
    needs: lint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./Backend
    strategy:
      matrix:
        java: [ 23 ]

    name: Run tests on Java ${{ matrix.java }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: run unit tests
        run: mvn clean test -PUnit

      - name: run integration tests
        run: mvn clean test -PIntegration
