name: GutHub Frontend

on:
  push:
    paths:
      - .github/**
      - Frontend/**

jobs:
  lint:
    runs-on: ubuntu-22.04

    name: Lint
    steps:
      - name: lint here
        run: echo "linting . . ."

  analysis:
    needs: lint
    runs-on: ubuntu-22.04

    name: Static code analysis
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Sonarcloud scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./Frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}

  test:
    needs: analysis
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./Frontend

    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: npm
          cache-dependency-path: ./Frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

  build:
    needs: test
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./Frontend

    name: Build
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: npm
          cache-dependency-path: ./Frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: guthub-frontend-build
          path: ./Frontend/dist/frontend
