name: GutHub Frontend

on:
  push:
    paths:
      - .github/**
      -  Frontend/**

jobs:
  lint:
    runs-on: ubuntu-22.04

    name: Lint
    steps:
      - name: lint here
        run: echo "linting . . ."

  test:
    needs: lint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./Frontend

    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0
          cache: npm
          cache-dependency-path: ./Frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci